/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-07 16:11:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class quick_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("<title>M CALL</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/jquery-ui-1.10.3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/font.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/common.css?<?=$strRenew?>\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/mcall.css?<?=$strRenew?>\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.animate.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-ui-1.10.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-ui-datepicker-ko.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.bpopup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/printThis.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/global.js?<?=$strRenew?>\"></script>\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" name=\"frm\" id=\"frm\" action=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"pageaction\" id=\"pageaction\" value=\"stockAG\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_phone_seq\" id=\"frm_phone_seq\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_start_shop_seq\" id=\"frm_start_shop_seq\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_color\" id=\"frm_color\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_usim_yn\" id=\"frm_usim_yn\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_etc\" id=\"frm_etc\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_memo\" id=\"frm_memo\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_model\" id=\"frm_model\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_wide_yn\" id=\"frm_wide_yn\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_quick_shop_seq1\" id=\"frm_quick_shop_seq1\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_quick1\" id=\"frm_quick1\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_quick_shop_seq2\" id=\"frm_quick_shop_seq2\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_quick2\" id=\"frm_quick2\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_start\" id=\"frm_start\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_start_hp\" id=\"frm_start_hp\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_start_post_no\" id=\"frm_start_post_no\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_start_addr\" id=\"frm_start_addr\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_start_addr_detail\" id=\"frm_start_addr_detail\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_finish_shop_seq\" id=\"frm_finish_shop_seq\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_end\" id=\"frm_end\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_end_hp\" id=\"frm_end_hp\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_end_post_no\" id=\"frm_end_post_no\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_end_addr\" id=\"frm_end_addr\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_end_addr_detail\" id=\"frm_end_addr_detail\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"frm_pay_tp\" id=\"frm_pay_tp\" value=\"\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<div id='wrap'>\r\n");
      out.write("\t\t<div id='lnb'>\r\n");
      out.write("\t\t\t<h1><a href='/main.html'><img src='/images/common/logo.png' /></a></h1>\r\n");
      out.write("\t\t\t<h2>퀵 서비스</h2>\r\n");
      out.write("\t\t\t<ul class='sub'>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- if($DS_USER['SHOP_TP'] == 'SH_AG') -->\r\n");
      out.write("\t\t\t\t<li class=''><a href='/page/quick/stockAG.html'>재고 퀵 요청하기</a></li>\r\n");
      out.write("\t\t\t\t<li class='sel'><a href='/page/quick/quick.html'>퀵 요청하기</a></li>\r\n");
      out.write("\t\t\t\t<li class=''><a href='/page/quick/manageAG.html'>재고 & 퀵 관리</a></li>\r\n");
      out.write("\t\t\t\t<li class=''><a href='/page/quick/record.html'>요청이력</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id='contain'>\r\n");
      out.write("\t\t\t<div class=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=''><a href='/page/quick/stockAG.html'>퀵 서비스</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=''><a href='/page/stock/stock.html'>재고관리</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=''><a href='/page/stock/stock.html'>정산</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=''><a href='/page/stock/stock.html'>고객관리</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=''><a href='/page/stock/stock.html'>일정</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=''><a href='/page/stock/stock.html'>설정</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<a href='javascript:doLogout();'>로그아웃</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id='content_wrap'> <!-- 100%의 전체 컨텐츠 영역-->\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t\t\tgetNowDatetime();\r\n");
      out.write("\t\t\t\t\t\tsetInterval(\"getNowDatetime()\", 1000);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction getNowDatetime(){\r\n");
      out.write("\t\t\t\t\t\tvar date = new Date();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar month = date.getMonth() + 1;\r\n");
      out.write("\t\t\t\t\t\tvar day = date.getDate();\r\n");
      out.write("\t\t\t\t\t\tvar hour = date.getHours();\r\n");
      out.write("\t\t\t\t\t\tvar minute = date.getMinutes();\r\n");
      out.write("\t\t\t\t\t\tvar sec = date.getSeconds();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar arrWeek = new Array('일', '월', '화', '수', '목', '금', '토');\r\n");
      out.write("\t\t\t\t\t\tvar week = date.getDay();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$('.now_time').html(month +'월 '+ day +'일 ('+ arrWeek[week] +') '+ hour +'시 '+ minute +'분 '+ sec +'초');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class='now_bx'>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<dt><!-- ><?=date('Y-m')?> --> 2019-09</dt>\r\n");
      out.write("\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>입고 <em class='current_num m5'><!-- <?=number_format($DS_GOODS_STAT['GD_IN'])?> -->0</em> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class='pl15'>단말기 <em class='current_num m5'><!-- <?=number_format($DS_GOODS_STAT['PHONE'])?> -->0</em></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class='pl15'>유심 <em class='current_num m5'><!-- <?=number_format($DS_GOODS_STAT['USIM'])?> -->0</em></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class='pl15'>개통 <em class='current_num m5'><!-- <?=number_format($DS_GOODS_STAT['GD_OP'])?> -->0</em></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class='now_time'><!-- getNowDatetime() --></p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class='pay'>퀵 잔액 : <em><?=number_format($DS_USER['AMT'])?>원</em></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href='/page/point/point.php' class='btn_charge'>충전하기</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href='/page/point/point_record.php' class='btn_his'>내역보기</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class='content'> <!-- 원하는 컨텐츠 넓이를 추가 w960 클래스는 width:960px란 의미 -->\r\n");
      out.write("\t\t\t\t<h2>퀵 요청하기</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class='tab_01 mt20'>\r\n");
      out.write("\t\t\t\t\t<li class=\"viewAddArea sel\" data-type=\"direct\"><a href='javascript:;'>직접 입력</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"viewAddArea\" data-type=\"recent\"><a href='javascript:;'>최근 요청</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 직접입력 -->\r\n");
      out.write("\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='tb_01_non mt20' id=\"table_direct\">\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t            \t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='15%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='15%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='15%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='15%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='20%' />\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">통신사</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">모델명</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">색상</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">유심필요</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">비고</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">출발지 선택 </th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">출발지 정보</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name='rc_telecom' id='rc_telecom_SKT' type='radio' value='1' onclick='javascript:selTelecom();' data-icon='/_upload/telecom/201707/83b0719b855216e218d0bbfb6862f4737fd708cb.png' /> SKT<span class='ml5'>\r\n");
      out.write("\t\t\t\t\t\t\t<input name='rc_telecom' id='rc_telecom_KT' type='radio' value='2' onclick='javascript:selTelecom();' data-icon='/_upload/telecom/201707/b7afce9daabba7d6ba62f235d20611f32c413da2.png' /> KT</span><span class='ml5'>\r\n");
      out.write("\t\t\t\t\t\t\t<input name='rc_telecom' id='rc_telecom_LGT' type='radio' value='3' onclick='javascript:selTelecom();' data-icon='/_upload/telecom/201708/cb55fe5a549bf4275123c067f9563746221e1ff9.png' /> LGT</span>\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div class='bx1'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"model\" id=\"model\" type=\"text\" onkeyup=\"javascript:doAutoCompleteModel();\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"autocomplete\" class=\"bx_area1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- ajax : doAutoCompleteModel()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">회사명</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">케이스업체</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">보호필름업체</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"color\" id=\"color\" class='w90p' onchange=\"javascript:getStartShop();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">선택하세요</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"usim_yn\" name=\"usim_y\" type=\"radio\" value=\"Y\" checked /> 유\r\n");
      out.write("\t\t\t\t\t\t\t<span class='ml5'><input name=\"usim_yn\" name=\"usim_n\" type=\"radio\" value=\"N\" /> 무</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"etc\" id=\"etc\" type=\"text\" class='w90p'/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"start_shop\" id=\"start_shop\" class='w90p' onchange=\"javascript:selShopInfo();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">선택하세요</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"start_info_td\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"phone_seq\" id=\"phone_seq\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"start\" id=\"start\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"start_hp\" id=\"start_hp\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"start_post_no\" id=\"start_post_no\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"start_addr\" id=\"start_addr\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"start_addr_detail\" id=\"start_addr_detail\" value=\"\">\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 최근요청 -->\r\n");
      out.write("\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='tb_01_non mt20' id=\"table_recent\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width='5%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='15%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='15%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='15%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='20%' />\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">&nbsp;</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">통신사</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">모델명</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">색상</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">유심필요</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">비고</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">출발지</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">출발지 정보</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class='center mt20'><input name=\"btnAdd\" type=\"button\" value='추가' class='btn_01 w200' onclick=\"javascript:addGoods();\" /></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class='num_txt mt30'>요청개수 <em>0</em></div>\r\n");
      out.write("\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='tb_01 mt10' id=\"main_table\">\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='18%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='18%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='18%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='16%' />\r\n");
      out.write("\t\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">통신사</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">모델명</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">색상</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">유심필요</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">비고</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">출발지</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">취소</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- ajax loading: addGoods() -->\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class='mt20'>\r\n");
      out.write("\t\t\t\t\t<select name=\"finish_shop_seq\" id=\"finish_shop_seq\" class='w10p' onchange=\"javascript:selFinishInfo();\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">도착지 선택</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input name=\"end_hp\" id=\"end_hp\" type=\"text\" placeholder='도착지 이동번호' class='w30p' readonly maxlength=\"15\" />\r\n");
      out.write("\t\t\t\t\t<input name=\"end_info\" id=\"end_info\" type=\"text\" placeholder='도착지 주소' class='w58p' readonly />\r\n");
      out.write("\t\t\t\t\t<input name=\"end\" id=\"end\" type=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t<input name=\"end_post_no\" id=\"end_post_no\" type=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t<input name=\"end_addr\" id=\"end_addr\" type=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t<input name=\"end_addr_detail\" id=\"end_addr_detail\" type=\"hidden\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class='memo_bx mt20 center'>\r\n");
      out.write("\t\t\t\t\t<span>메모</span>\r\n");
      out.write("\t\t\t\t\t<input name=\"memo\" id=\"memo\" type=\"text\" class='w50p mr10' value=\"\" />\r\n");
      out.write("\t\t\t\t\t<input name=\"pay_tp\" id=\"pay_tp_ls\" type=\"radio\" value=\"QC_LS\" data-str=\"착불\" /> 착불 <span class='m30'><input name=\"pay_tp\" id=\"pay_tp_fs\" type=\"radio\" value=\"QC_FS\" data-str=\"차감\" checked /> 차감</span>\r\n");
      out.write("\t\t\t\t\t<input name=\"\" type=\"button\" value='퀵요청' class='btn_02 w80 ml10' onclick=\"javascript:openReqPopup();\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--// content -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--// 전체 100% CONTENTS\t -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--//contain-->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--//wrap-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- popup -->\r\n");
      out.write("\t<div id=\"pop_quick_stock_request\" class=\"dialog-popup\" style=\"width:900px;\">\r\n");
      out.write("\t\t<div id='pop'>\r\n");
      out.write("\t\t\t<div class='title'>\r\n");
      out.write("\t\t\t\t<h2>재고퀵요청</h2>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:CLOSE_LAYER_POPUP('#pop_quick_stock_request');\" class='pop_close'>닫기</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='tb_01_non mt10'>\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width='20%' />\r\n");
      out.write("\t\t\t\t\t<col width='30%' />\r\n");
      out.write("\t\t\t\t\t<col width='20%' />\r\n");
      out.write("\t\t\t\t\t<col width='30%' />\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">도착지</th>\r\n");
      out.write("\t\t\t\t\t<td class='lf2' id=\"end_str\">효목탑</td>\r\n");
      out.write("\t\t\t\t\t<th>결제형태</th>\r\n");
      out.write("\t\t\t\t\t<td class='lf2' id=\"pay_tp_str\">차감</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='tb_01' id=\"pop_req_table\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t\t\t<col width='15%' />\r\n");
      out.write("\t\t\t\t\t<col width='25%' />\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">광역퀵</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">출발지</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">통신사</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">모델명</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">색상</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">유심</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">비고</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">광역출발지퀵</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<!-- script : addGoods() -->\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<dl class='memo mt10'>\r\n");
      out.write("\t\t\t\t<dt><span>메모</span></dt>\r\n");
      out.write("\t\t\t\t<dd></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class='pop_txt'>\r\n");
      out.write("\t\t\t\t<p>위 정보로 퀵 요청하시겠습니까?</p>\r\n");
      out.write("\t\t\t\t<div class='bx3 w300' >\r\n");
      out.write("\t\t\t\t\t<select name=\"quick_shop_seq1_sel\" id=\"quick_shop_seq1_sel\" class=\"w30p\" onchange=\"javascript:selQuick1('');\">\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"quick1\" id=\"quick1\" class=\"w60p\" readonly>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"quick_shop_seq1\" id=\"quick_shop_seq1\" value=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type='button' value='퀵요청' class='btnp_01 w120' onclick=\"javascript:doGoodsReq();\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"pop_quick_search\" class=\"dialog-popup\" style=\"width:600px;\">\r\n");
      out.write("\t\t<div id='pop'>\r\n");
      out.write("\t\t\t<div class='title'>\r\n");
      out.write("\t\t\t\t<h2>퀵업체검색</h2>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:CLOSE_LAYER_POPUP('#pop_quick_search');\" class='pop_close'>닫기</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<select name=\"pop_sch_type\" id=\"pop_sch_type\" class='w130'>\r\n");
      out.write("\t\t\t\t\t<option value=\"SHOP_ADDR\">지역</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"SHOP_NM\">회사명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"SHOP_ID\">아이디</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<div class='bx3 w330' >\r\n");
      out.write("\t\t\t\t\t<input name=\"pop_sch_text\" id=\"pop_sch_text\" type=\"text\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type='button' value='검색' class='btnp_01 w100' onclick=\"javascript:getQuickShop();\" />\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"pop_quick_search_ajax\">\r\n");
      out.write("\t\t\t\t<!-- ajax loading: showQuickSearch() -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
