/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-10 12:57:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/common_inc/left_menu_inc.jsp", Long.valueOf(1570703640158L));
    _jspx_dependants.put("/common_inc/top_menu_inc.jsp", Long.valueOf(1570703830890L));
    _jspx_dependants.put("/common_inc/html_footer_inc.jsp", Long.valueOf(1570703420808L));
    _jspx_dependants.put("/common_inc/html_top_inc.jsp", Long.valueOf(1570712091019L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("<title>M CALL</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/jquery-ui-1.10.3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/font.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/common.css?<?=$strRenew?>\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/mcall.css?<?=$strRenew?>\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jquery.animate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jquery-ui-1.10.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jquery-ui-datepicker-ko.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jquery.bpopup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/printThis.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/global.js?<?=$strRenew?>\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t//h.tml\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t// IE9 이하 버전 업그레이드 경고창\r\n");
      out.write("\t\tif( $.browser.msie == true && $.browser.version <= 9){\r\n");
      out.write("\t\t\talert('IE10 버전 이상으로 업데이트해주세요.');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t// 특정영역인쇄[공통]\r\n");
      out.write("\tfunction AREA_PRINT(selector){\r\n");
      out.write("\t\t$(selector).printThis({\r\n");
      out.write("\t\t\tdebug: false,               // show the iframe for debugging\r\n");
      out.write("\t\t\timportCSS: true,            // import page CSS\r\n");
      out.write("\t\t\timportStyle: false,         // import style tags\r\n");
      out.write("\t\t\tprintContainer: true,       // grab outer container as well as the contents of the selector\r\n");
      out.write("\t\t\tloadCSS: [\"/css/common.css\",\"/css/mcall.css\"],  // path to additional css file - use an array [] for multiple\r\n");
      out.write("\t\t\tpageTitle: \"\",              // add title to print page\r\n");
      out.write("\t\t\tremoveInline: false,        // remove all inline styles from print elements\r\n");
      out.write("\t\t\tprintDelay: 333,            // variable print delay; depending on complexity a higher value may be necessary\r\n");
      out.write("\t\t\theader: null,               // prefix to html\r\n");
      out.write("\t\t\tfooter: null,               // postfix to html\r\n");
      out.write("\t\t\tbase: false ,               // preserve the BASE tag, or accept a string for the URL\r\n");
      out.write("\t\t\tformValues: true,           // preserve input/form values\r\n");
      out.write("\t\t\tcanvas: false,              // copy canvas elements (experimental)\r\n");
      out.write("\t\t\tdoctypeString: \"...\",       // enter a different doctype for older markup\r\n");
      out.write("\t\t\tremoveScripts: false        // remove script tags from print content\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//h.html\r\n");
      out.write("\r\n");
      out.write("\tvar YMD = GET_DATE_YMD();\r\n");
      out.write("\tvar S_SHOP_TP = '<?=$S_SHOP_TP?>';\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tgetCalendar(YMD);\r\n");
      out.write("\t\t$('#div_'+ S_SHOP_TP).show();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/* 달력영역 */\r\n");
      out.write("\t// 달력 불러오기\r\n");
      out.write("\tfunction getCalendar(date){\r\n");
      out.write("\t\tconsole.log(date);\r\n");
      out.write("\t\tvar year = date.substring(0, 4);\r\n");
      out.write("\t\tvar month = date.substring(4, 6);\r\n");
      out.write("\r\n");
      out.write("\t\tvar url = \"main_calendar_ajax.php\";\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\tyear: year\r\n");
      out.write("\t\t\t, month: month\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tdataType : 'html',\r\n");
      out.write("\t\t\turl: url,\r\n");
      out.write("\t\t\tdata: param,\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tsuccess: function(obj){\r\n");
      out.write("\t\t\t\t//console.log(obj.data);\r\n");
      out.write("\t\t\t\t$('.tb_mcal').remove();\r\n");
      out.write("\t\t\t\t$('#year_month').html(year +'.'+ month);\r\n");
      out.write("\t\t\t\t$('.m_cal').append(obj);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(request, status, error){\r\n");
      out.write("\t\t\t\t//alert('Find Error -> '+ status);\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t//console.log(request);\r\n");
      out.write("\t\t\t\t//console.log(status);\r\n");
      out.write("\t\t\t\t//console.log(error);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 이전월 이동\r\n");
      out.write("\tfunction goPrevMonth(){\r\n");
      out.write("\t\tYMD = GET_MOVE_DATE(YMD, 'month', -1);\r\n");
      out.write("\t\tgetCalendar(YMD);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 다음월 이동\r\n");
      out.write("\tfunction goNextMonth(){\r\n");
      out.write("\t\tYMD = GET_MOVE_DATE(YMD, 'month', 1);\r\n");
      out.write("\t\tgetCalendar(YMD);\r\n");
      out.write("\t}\r\n");
      out.write("\t/* 달력영역 */\r\n");
      out.write("\r\n");
      out.write("\t// 공지사항 상세이동\r\n");
      out.write("\tfunction goNoticeDetail(board_seq){\r\n");
      out.write("\t\talert('준비중입니다');\r\n");
      out.write("\t\t//location.href = \"\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id='wrap'>\r\n");
      out.write("\t<!-- 왼쪽메뉴 [START] -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div id='lnb'>\r\n");
      out.write("\t<h1><a href='/'><img src='/images/common/logo.png' /></a></h1>\r\n");
      out.write("\t<dl class='member_info'>\r\n");
      out.write("\t\t<dt><span>경북대<!--=$S_STAFF_ID--></span> 님의 정보</dt>\r\n");
      out.write("\t\t<dd>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>이름 : <span><!--=$S_STAFF_NM-->박제영</span></li>\r\n");
      out.write("\t\t\t\t<li>아이디 타입 : <span><!--=$S_SHOPID_YN == 'Y' ? '업체' : '직원'-->직원</span></li>\r\n");
      out.write("\t\t\t\t<li><!--=$S_SHOPID_YN == 'Y' ? '상호' : '소속'-->상호 : <span><!--=$S_SHOP_NM-->경북대 8조</span></li>\r\n");
      out.write("\t\t\t\t<li>권한 : <span><!--=CODE_STAFF_GRADE($S_GRADE)--></span></li>\r\n");
      out.write("\t\t\t\t<li>최종접속일시 : <p><!--=$S_LAST_ACC_DT-->2019-09-28 12:00:00</p></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</dd>\r\n");
      out.write("\r\n");
      out.write("\t\t<dt>소속 계정 정보</dt>\r\n");
      out.write("\t\t<dd>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>타입 : <span><!--=CODE_SHOP_TP($S_SHOP_TP)-->대리점or판매점</span></li>\r\n");
      out.write("\t\t\t\t<li>거래 대리점 : <span><!--=$dsDeal['AGENT_CNT']-->0 개</span></li>\r\n");
      out.write("\t\t\t\t<li>소속 판매점 : <span><!--=$dsLow['CNT']-->0 개</span></li>\r\n");
      out.write("\t\t\t\t<li>거래 판매점 : <span><!--=$dsDeal['SALE_CNT']-->0 개</span></li>\r\n");
      out.write("\t\t\t\t<li>입고처 : <span><!--=$dsInplace['CNT']-->0 개</span></li>\r\n");
      out.write("\t\t\t\t<li>직원 : <span><!--=$dsStaff['CNT']-->0 명</span></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</dd>\r\n");
      out.write("\t</dl>\r\n");
      out.write("\r\n");
      out.write("\t<ul class='m_down'>\r\n");
      out.write("\t\t<li><a href='#'>공시지원금</a></li>\r\n");
      out.write("\t\t<li><a href='#'>M CALL 앱</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t<dl class='m_cus'>\r\n");
      out.write("\t\t<dt>고객센터</dt>\r\n");
      out.write("\t\t<dd><a href='#'>데이터 대량등록</a></dd>\r\n");
      out.write("\t</dl>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t<!-- 왼쪽 메뉴 [ END ] -->\r\n");
      out.write("\t<div id='contain'>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 상단메뉴 [START] -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<div class=\"gnb\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li class=''><a href=/page/quick/quick>퀵 서비스</a></li>\r\n");
      out.write("\t\t<li class=''><a href=/page/stock/stock>재고관리</a></li>\r\n");
      out.write("\t\t<li class=''><a href=/page/stock/stock>정산</a></li>\r\n");
      out.write("\t\t<li class=''><a href=/page/stock/stock>고객관리</a></li>\r\n");
      out.write("\t\t<li class=''><a href=/page/stock/stock>일정</a></li>\r\n");
      out.write("\t\t<li class=''><a href=/page/stock/stock>설정</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<a href='javascript:doLogout();'>로그아웃</a>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t<!-- 상단메뉴 [END] -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id='content_wrap'> <!-- 100%의 전체 컨텐츠 영역-->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t\tgetNowDatetime();\r\n");
      out.write("\t\t\t\t\tsetInterval(\"getNowDatetime()\", 1000);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfunction getNowDatetime(){\r\n");
      out.write("\t\t\t\t\tvar date = new Date();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar month = date.getMonth() + 1;\r\n");
      out.write("\t\t\t\t\tvar day = date.getDate();\r\n");
      out.write("\t\t\t\t\tvar hour = date.getHours();\r\n");
      out.write("\t\t\t\t\tvar minute = date.getMinutes();\r\n");
      out.write("\t\t\t\t\tvar sec = date.getSeconds();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar arrWeek = new Array('일', '월', '화', '수', '목', '금', '토');\r\n");
      out.write("\t\t\t\t\tvar week = date.getDay();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('.now_time').html(month +'월 '+ day +'일 ('+ arrWeek[week] +') '+ hour +'시 '+ minute +'분 '+ sec +'초');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div class='now_bx'>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<dt><!-- ><?=date('Y-m')?> --> 2019-09</dt>\r\n");
      out.write("\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>입고 <em class='current_num m5'><!-- <?=number_format($DS_GOODS_STAT['GD_IN'])?> -->0</em> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class='pl15'>단말기 <em class='current_num m5'><!-- <?=number_format($DS_GOODS_STAT['PHONE'])?> -->0</em></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class='pl15'>유심 <em class='current_num m5'><!-- <?=number_format($DS_GOODS_STAT['USIM'])?> -->0</em></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class='pl15'>개통 <em class='current_num m5'><!-- <?=number_format($DS_GOODS_STAT['GD_OP'])?> -->0</em></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class='now_time'><!-- getNowDatetime() --></p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class='pay'>퀵 잔액 : <em><?=number_format($DS_USER['AMT'])?>원</em></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href='/page/point/point.php' class='btn_charge'>충전하기</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href='/page/point/point_record.php' class='btn_his'>내역보기</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div class='content'> <!-- 원하는 컨텐츠 넓이를 추가 w960 클래스는 width:960px란 의미 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div class='m_situ'>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<div class='m_01'>\r\n");
      out.write("\t\t\t\t\t\t<h2>퀵 서비스 <em><!-- <?=number_format($sumQuick)?> -->0</em></h2>\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='m_tb'>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">요청중</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- ><?=number_format($dsTopStat1['REQUEST'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">배송중</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat1['DELIVER'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">배송완료</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat1['COMPLETE'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<!-- 도매대리점일 경우(현재 기준) -->\r\n");
      out.write("\t\t\t\t\t<div class='m_02' id=\"div_SH_AG\" style=\"display:block;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"m_02_div\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>입고 <em><!-- <?=number_format($sumIn)?> -->0</em></h2>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='m_tb'>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">단말기</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat2['IN_PHONE_CNT'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">유심</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat2['IN_USIM_CNT'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"m_02_div\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>출고 <em><!-- <?=number_format($sumOut)?> -->0</em></h2>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='m_tb'>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">단말기</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat2['OUT_PHONE_CNT'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">유심</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat2['OUT_USIM_CNT'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- //도매대리점일 경우 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<!-- 판매점일 경우 -->\r\n");
      out.write("\t\t\t\t\t<div class='m_04' id=\"div_SH_SA\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>재고 <em><!-- <?=number_format($sumGoods)?> -->0</em></h2>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='m_tb'>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">단말기</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat2['PHONE_CNT'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">유심</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat2['USIM_CNT'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--// 판매점일 경우 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<!-- 개통현황 경우 -->\r\n");
      out.write("\t\t\t\t\t<div class='m_03'>\r\n");
      out.write("\t\t\t\t\t\t<h2><!-- <?=$nowMonth?> -->9월 개통현황 <em><!-- <?=$sumOpen?> -->0</em></h2>\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='m_tb'>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='50%'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='25%'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width='25%'>\r\n");
      out.write("\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">신규</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat3['OP_CNT'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">번호이동</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat3['MV_CNT'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">재가입(기변)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><!-- <?=number_format($dsTopStat3['RE_CNT'])?> -->0</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 개통현황 경우 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div class='m_situ2'>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<div class='m_cal'>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href='javascript:goPrevMonth();'><img src='/images/main/btn_calpre.png' /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"year_month\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<a href='javascript:goNextMonth();'><img src='/images/main/btn_calnext.png' /></a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<!-- calendar ajax load : main_calendar_ajax.php -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<div class='m_noti'>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 대리점일 경우 -->\r\n");
      out.write("\t\t\t\t\t\t<div class='noti_bx'>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>공지사항</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:goNoticeDetail('<?=$ds['SEQ']?>');\"><!-- <?=$ds['TITLE']?> -->공지1</a> <span><!-- <?=substr($ds['REG_DT'], 2, 8)?> -->2019-09-28</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:goNoticeDetail('<?=$ds['SEQ']?>');\"><!-- <?=$ds['TITLE']?> -->공지2</a> <span><!-- <?=substr($ds['REG_DT'], 2, 8)?> -->2019-09-28</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:goNoticeDetail('<?=$ds['SEQ']?>');\"><!-- <?=$ds['TITLE']?> -->공지3</a> <span><!-- <?=substr($ds['REG_DT'], 2, 8)?> -->2019-09-28</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:goNoticeDetail('<?=$ds['SEQ']?>');\"><!-- <?=$ds['TITLE']?> -->공지4</a> <span><!-- <?=substr($ds['REG_DT'], 2, 8)?> -->2019-09-28</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:goNoticeDetail('<?=$ds['SEQ']?>');\"><!-- <?=$ds['TITLE']?> -->공지5</a> <span><!-- <?=substr($ds['REG_DT'], 2, 8)?> -->2019-09-28</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p><a href='#'><img src='/images/main/btn_more.png' /></a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--// 대리점일 경우 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 판매점일 경우 -->\r\n");
      out.write("\t\t\t\t\t\t<div class='m_agency'>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>대리점 정책</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='m_tbag'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width='33.3333%' />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width='33.3333%' />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width='33.3333%' />\r\n");
      out.write("\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">등록일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">적용일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">대리점</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><?=substr($ds['REG_DT'], 0, 10)?>2019-09-28</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><?=substr($ds['POLICY_DT'], 0, 10)?>2019-09-28</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><?=$ds['SHOP_NM']?>대리점1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><?=substr($ds['REG_DT'], 0, 10)?>2019-09-28</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><?=substr($ds['POLICY_DT'], 0, 10)?>2019-09-28</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><?=$ds['SHOP_NM']?>대리점2</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><?=substr($ds['REG_DT'], 0, 10)?>2019-09-28</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><?=substr($ds['POLICY_DT'], 0, 10)?>2019-09-28</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><?=$ds['SHOP_NM']?>대리점3</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t<p><a href='/page/setting/agency.php'><img src='/images/main/btn_more.png' /></a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--// 판매점일 경우 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--// content -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--// 전체 100% CONTENTS\t -->\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--//contain-->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--//wrap-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 공지사항 팝업 -->\r\n");
      out.write("<div id=\"pop_quick_notice\" class=\"dialog-popup\" style=\"width:900px;\">\r\n");
      out.write("\t<div id='pop'>\r\n");
      out.write("\t\t<div class='title'>\r\n");
      out.write("\t\t\t<h2>공지사항 상세보기</h2>\r\n");
      out.write("\t\t\t<a href=\"javascript:hideGoodsReqPopup();\" class='pop_close'>닫기</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='tb_02'>\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width='34%' />\r\n");
      out.write("\t\t\t\t<col width='33%' />\r\n");
      out.write("\t\t\t\t<col width='33%' />\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">요청점</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">처리자</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">상태</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr id=\"goods_req_tr_top\">\r\n");
      out.write("\t\t\t\t<!-- ajax loading\r\n");
      out.write("\t\t\t\t<td>효목탑</td>\r\n");
      out.write("\t\t\t\t<td>마이콜</td>\r\n");
      out.write("\t\t\t\t<td>부분완료</td>\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='tb_01 mt20' id=\"goods_req_table_list\">\r\n");
      out.write("\t\t\t<!-- ajax loading\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width='16%' />\r\n");
      out.write("\t\t\t\t<col width='20%' />\r\n");
      out.write("\t\t\t\t<col width='16%' />\r\n");
      out.write("\t\t\t\t<col width='16%' />\r\n");
      out.write("\t\t\t\t<col width='22%' />\r\n");
      out.write("\t\t\t\t<col width='10%' />\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">통신사</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">모델명</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">색상</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">비고</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">퀵요청</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">취소</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><img src='/images/common/icon_t.png' /></td>\r\n");
      out.write("\t\t\t\t<td>SM-N930</td>\r\n");
      out.write("\t\t\t\t<td>블랙</td>\r\n");
      out.write("\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td><a href='#' class='s_btn3 w80'>요청하기</a></td>\r\n");
      out.write("\t\t\t\t<td><a href='#' class='s_btn2 w40'>취소</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><img src='/images/common/icon_uplus.png' /></td>\r\n");
      out.write("\t\t\t\t<td>SM-N930</td>\r\n");
      out.write("\t\t\t\t<td>블랙</td>\r\n");
      out.write("\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td>N201610190001</td>\r\n");
      out.write("\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t -->\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div class='memo_bx mt20 center'>\r\n");
      out.write("\t\t\t<span>메모</span>\r\n");
      out.write("\t\t\t<input name=\"goods_req_memo\" id=\"goods_req_memo\" type=\"text\"  class='w87p' value=\"\" />\r\n");
      out.write("\t\t\t<input type=\"button\" value='저장' class='btn_02 w60' onclick=\"javascript:doSaveGoodsReqMemo('#goods_req_memo');\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<form method=\"post\" name=\"frm\" id=\"frm\" action=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"pageaction\" id=\"pageaction\" value=\"stockAG\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_phone_seq\" id=\"frm_phone_seq\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_start_shop_seq\" id=\"frm_start_shop_seq\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_color\" id=\"frm_color\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_usim_yn\" id=\"frm_usim_yn\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_etc\" id=\"frm_etc\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_memo\" id=\"frm_memo\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_model\" id=\"frm_model\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_wide_yn\" id=\"frm_wide_yn\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_quick_shop_seq1\" id=\"frm_quick_shop_seq1\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_quick1\" id=\"frm_quick1\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_quick_shop_seq2\" id=\"frm_quick_shop_seq2\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_quick2\" id=\"frm_quick2\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_start\" id=\"frm_start\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_start_hp\" id=\"frm_start_hp\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_start_post_no\" id=\"frm_start_post_no\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_start_addr\" id=\"frm_start_addr\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_start_addr_detail\" id=\"frm_start_addr_detail\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_finish_shop_seq\" id=\"frm_finish_shop_seq\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_end\" id=\"frm_end\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_end_hp\" id=\"frm_end_hp\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_end_post_no\" id=\"frm_end_post_no\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_end_addr\" id=\"frm_end_addr\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_end_addr_detail\" id=\"frm_end_addr_detail\" value=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"frm_pay_tp\" id=\"frm_pay_tp\" value=\"\">\r\n");
      out.write("\t</form>\t\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
